base:
    seed: &seed 0
model:
    type: IndustrialCoder
    path: /mnt/lm_data_afs/wangzining/charles/lab/llmc/thinkingmodel/IndustrialCoder-Thinking
    torch_dtype: auto
calib:
    name: wikitext2
    download: True
    n_samples: 128
    # path: calib data path
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: True
    # path: eval data path
    bs: 1
    seq_len: 2048
    inference_per_block: False
quant:
    method: GPTQ
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        need_pack: True
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        true_sequential: True
    quant_out: True
save:
    save_vllm: True
    save_path: /mnt/lm_data_afs/wangzining/charles/lab/llmc/save_for_vllm/thinking_gptq_w4/
