base:
    seed: &seed 42
model:
    type: Qwen2
    path: /home/gushiqiao/nvme/gushiqiao/bussinesss/code_72b/SenseChat-Code-Tmp
    tokenizer_mode: fast
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /home/gushiqiao/nvme/gushiqiao/llm_datasets/calib/pileval
    n_samples: 256
    bs: -1
    seq_len: 512
    preproc: txt_general_preproc
    seed: *seed
# eval:
#     - eval_pos: [ fake_quant]
#       name: wikitext2
#       download: False
#       path: /home/gushiqiao/nvme/gushiqiao/llm_datasets/eval/wikitext2
#       seq_len: 2048
#       # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
#       # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
#       bs: 10
#       inference_per_block: True
quant:
    method: Awq
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        trans: True
        trans_version: v2
        weight_clip: False
        awq_bs: 128
    quant_out: True
save:
    save_trans: True
    save_path: ./awq_test_new_pileval_down_ov/
