base:
    seed: &seed 42
model:
    type: Llama
    path: model path
    torch_dtype: auto
calib:
    name: pileval
    download: False
    n_samples: 128
    path: valib data path
    bs: 1
    seq_len: 512
    preproc: general
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: [wikitext2, c4]
    download: False
    path: eval data path
    bs: 1
    inference_per_block: False
    seq_len: 2048
quant:
    method: GPTQ
    weight:
        bit: 6
        symmetric: False
        granularity: per_channel
        group_size: -1
        qmax_to_tensor: True
        calib_algo: minmax
    act:
        bit: 6
        symmetric: False
        granularity: per_token
        qmax_to_tensor: True
        calib_algo: minmax
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        true_sequential: True
        online_rotate: True
        fp32_had: True
    quant_out: True
save:
    save_trans: False
    save_fake:  False
    save_path: ./save
