base:
    seed: &seed 42
model:
    type: Qwen3
    path: /home/michael/Project/models/Qwen3-0.6B
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /home/michael/Project/calib/pileval
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: txt_general_preproc
    seed: *seed
eval:
    eval_pos: [] #long_ppl eval not support pretrain eval pos
    name: wikitext2
    type: decode_ppl
    download: False
    path: /home/michael/Project/llmc_datasets/wikitext2
    bs: 1
    inference_per_block: False
    num_samples: 10
    # num_eval_tokens: 3
quant:
    method: RTN
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
    act:
        bit: 8
        symmetric: True
        granularity: per_tensor
        static: True
    kvcache:
        method: Naive
        bit: 8
        symmetric: True
        granularity: per_tensor
save:
    save_lightllm_kv_cache_calib: True
    lightllm_kv_cache_calib_name: kv_cache_calib.json
    save_fake: False
    save_path: /home/michael/Project/llmc_save
